python version: 3.6.9 (default, Jan 26 2021, 15:33:00)  [GCC 8.4.0]
pudb version: 2021.1
urwid version: 2.1.2
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pudb/debugger.py", line 2621, in event_loop
    toplevel.keypress(self.size, k)
  File "/usr/local/lib/python3.6/dist-packages/pudb/ui_tools.py", line 119, in keypress
    result = self._w.keypress(size, key)
  File "/usr/local/lib/python3.6/dist-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/lib/python3.6/dist-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/local/lib/python3.6/dist-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/local/lib/python3.6/dist-packages/pudb/ui_tools.py", line 124, in keypress
    return handler(self, size, key)
  File "/usr/local/lib/python3.6/dist-packages/pudb/debugger.py", line 1308, in next_line
    end()
  File "/usr/local/lib/python3.6/dist-packages/pudb/debugger.py", line 1300, in end
    self.debugger.save_breakpoints()
  File "/usr/local/lib/python3.6/dist-packages/pudb/debugger.py", line 283, in save_breakpoints
    for fn, bp_lst in self.get_all_breaks().items()
  File "/usr/local/lib/python3.6/dist-packages/pudb/settings.py", line 600, in save_breakpoints
    save_path = get_breakpoints_file_name()
  File "/usr/local/lib/python3.6/dist-packages/pudb/settings.py", line 563, in get_breakpoints_file_name
    save_path = get_save_config_path()
  File "/usr/local/lib/python3.6/dist-packages/pudb/settings.py", line 61, in get_save_config_path
    os.makedirs(path, 448)  # 0o700
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.config'

